### ISSUE TITLE
Joi breaks on node v10

### ISSUE THREAD

**Issue by trygve-lie** [metrics-js/prometheus-consumer#26]
Joi v17 has [dropped support for node v10](https://github.com/hapijs/joi/issues/2262) despite node [v10 are still in active development](https://nodejs.org/en/about/releases/). Together with Jest this is [breaking in our case](https://github.com/metrics-js/prometheus-consumer/pull/25).

There [seems to be others experiencing this also](https://github.com/hapijs/joi/issues/2264). Unless Joi is reverting its node v10 support I only see two options: drop node v10 support or drop Joi.

I kinda understands that one want to drop node v10 but its still under LTS and in active development. I would at least wait for May 2020 before dropping node v10 support. I am in favor of dropping Joi in this case.

**Comment by digitalsadhu** [comment]
Agree. Shouldn’t be a big job to drop Joi and it’s nice to remove a dep.

**Comment by Marsup** [comment]
No one is forcing you to bump major right now though.

**Comment by trygve-lie** [comment]
@Marsup I understand that. Though our situation is that we (the company we work for) have quite a lot of applications which now is more or less forced up on node 12 by a change in Joi. I am fine with that, but it takes time. Though; what do we do if there is a security bug in Joi pre 17 and we are half way moving to node 12?

I understand the will in the Hapi community to move beyond node 10 and I want so too in our modules and applications, but I find the way to move of node 10 which the Hapi community has chosen way too harsh by pushing a release which breaks straight away on a node version which are still under active development and LTS.

In this module is just easier for us to remove Joi. We have plenty of other modules where this is going to be a much bigger pain for us.

**Comment by Marsup** [comment]
Just to be sure we understand each other, what I meant is you can stick to joi@16 until you're comfortable to move on, security issues should be backported to 16 long enough for you to do that.

**Comment by trygve-lie** [comment]
Removed in #27
